"""
This type stub file was generated by pyright.
"""

import sys

"""
This type stub file was generated by pyright.
"""
if sys.version_info[: 2] >= (3, 0):
    def exec_file_wrapper(fpath, g_vars, l_vars):
        ...
    
