"""
This type stub file was generated by pyright.
"""

import cv2
from collections import namedtuple

"""
This type stub file was generated by pyright.
"""
NativeMethodPatchedResult = ...
def testOverwriteNativeMethod(arg):
    ...

