"""
This type stub file was generated by pyright.
"""

def gsutil_getsize(url=...): # -> Any | Literal[0]:
    ...

def attempt_download(file, repo=...): # -> None:
    ...

def gdrive_download(id=..., file=...): # -> int:
    ...

def get_token(cookie=...): # -> str:
    ...

