"""
This type stub file was generated by pyright.
"""

def fitness(x):
    ...

def ap_per_class(tp, conf, pred_cls, target_cls, v5_metric=..., plot=..., save_dir=..., names=...): # -> tuple[ndarray[Any, dtype[float64]], ndarray[Any, dtype[float64]], NDArray[float64], ndarray[Any, dtype[floating[Any]]], NDArray[Any]]:
    """ Compute the average precision, given the recall and precision curves.
    Source: https://github.com/rafaelpadilla/Object-Detection-Metrics.
    # Arguments
        tp:  True positives (nparray, nx1 or nx10).
        conf:  Objectness value from 0-1 (nparray).
        pred_cls:  Predicted object classes (nparray).
        target_cls:  True object classes (nparray).
        plot:  Plot precision-recall curve at mAP@0.5
        save_dir:  Plot save directory
    # Returns
        The average precision as computed in py-faster-rcnn.
    """
    ...

def compute_ap(recall, precision, v5_metric=...): # -> tuple[Any, NDArray[Any], NDArray[Any]]:
    """ Compute the average precision, given the recall and precision curves
    # Arguments
        recall:    The recall curve (list)
        precision: The precision curve (list)
        v5_metric: Assume maximum recall to be 1.0, as in YOLOv5, MMDetetion etc.
    # Returns
        Average precision, precision curve, recall curve
    """
    ...

class ConfusionMatrix:
    def __init__(self, nc, conf=..., iou_thres=...) -> None:
        ...
    
    def process_batch(self, detections, labels): # -> None:
        """
        Return intersection-over-union (Jaccard index) of boxes.
        Both sets of boxes are expected to be in (x1, y1, x2, y2) format.
        Arguments:
            detections (Array[N, 6]), x1, y1, x2, y2, conf, class
            labels (Array[M, 5]), class, x1, y1, x2, y2
        Returns:
            None, updates confusion matrix accordingly
        """
        ...
    
    def matrix(self): # -> () -> ...:
        ...
    
    def plot(self, save_dir=..., names=...): # -> None:
        ...
    
    def print(self): # -> None:
        ...
    


def plot_pr_curve(px, py, ap, save_dir=..., names=...): # -> None:
    ...

def plot_mc_curve(px, py, save_dir=..., names=..., xlabel=..., ylabel=...): # -> None:
    ...

